import { Company } from './types'

export const MOCK_COMPANIES: Company[] = [
  {
    id: '1',
    name: 'Anthropic',
    description: 'AI safety company building Claude, an advanced AI assistant.',
    website: 'anthropic.com',
    industry: 'AI & Machine Learning',
    stage: 'Late Stage',
    funding: 5700000000,
    signals: 'High',
    founders: ['Dario Amodei', 'Daniela Amodei'],
    employees: 500,
    yearFounded: 2021,
  },
  {
    id: '2',
    name: 'Scale AI',
    description: 'Data infrastructure platform for AI model development.',
    website: 'scale.com',
    industry: 'AI & Machine Learning',
    stage: 'Series D',
    funding: 7300000000,
    signals: 'High',
    founders: ['Alexandr Wang', 'Lucy Guo'],
    employees: 600,
    yearFounded: 2016,
  },
  {
    id: '3',
    name: 'Lattice',
    description: 'Talent management and employee engagement platform.',
    website: 'lattice.com',
    industry: 'HR & People',
    stage: 'Late Stage',
    funding: 375000000,
    signals: 'High',
    founders: ['Jack Altman', 'Matt Straz'],
    employees: 400,
    yearFounded: 2013,
  },
  {
    id: '4',
    name: 'Mercury',
    description: 'Modern banking platform for startups and creators.',
    website: 'mercury.com',
    industry: 'Fintech',
    stage: 'Series C',
    funding: 260000000,
    signals: 'High',
    founders: ['Rob Hayes', 'Alex Medick'],
    employees: 200,
    yearFounded: 2020,
  },
  {
    id: '5',
    name: 'Ribbon',
    description: 'Healthcare commerce platform connecting patients to services.',
    website: 'ribbonhealth.com',
    industry: 'Healthcare',
    stage: 'Series B',
    funding: 75000000,
    signals: 'Medium',
    founders: ['Steve Kramer'],
    employees: 150,
    yearFounded: 2014,
  },
  {
    id: '6',
    name: 'Replicabot',
    description: 'AI-powered customer support automation.',
    website: 'replicabot.ai',
    industry: 'AI & Machine Learning',
    stage: 'Series A',
    funding: 12000000,
    signals: 'High',
    founders: ['Emily Chen'],
    employees: 45,
    yearFounded: 2022,
  },
  {
    id: '7',
    name: 'Valence',
    description: 'Supply chain intelligence and optimization platform.',
    website: 'valencesoftware.com',
    industry: 'Supply Chain',
    stage: 'Series B',
    funding: 50000000,
    signals: 'Medium',
    founders: ['Dan Callahan'],
    employees: 80,
    yearFounded: 2020,
  },
  {
    id: '8',
    name: 'Vial',
    description: 'Clinical trial platform connecting patients and researchers.',
    website: 'vial.com',
    industry: 'Healthcare',
    stage: 'Series B',
    funding: 80000000,
    signals: 'High',
    founders: ['Reuben Harris', 'David Olshavsky'],
    employees: 120,
    yearFounded: 2019,
  },
  {
    id: '9',
    name: 'Muso',
    description: 'Music discovery and marketing platform for artists.',
    website: 'musoai.com',
    industry: 'Entertainment',
    stage: 'Series A',
    funding: 15000000,
    signals: 'Medium',
    founders: ['Isaac Cohen'],
    employees: 50,
    yearFounded: 2021,
  },
  {
    id: '10',
    name: 'Checkpoint',
    description: 'Software supply chain security platform.',
    website: 'checkpointsecurity.com',
    industry: 'Security & Compliance',
    stage: 'Series A',
    funding: 25000000,
    signals: 'High',
    founders: ['Omer Rosenbaum'],
    employees: 60,
    yearFounded: 2021,
  },
  {
    id: '11',
    name: 'Replo',
    description: 'No-code platform for e-commerce businesses.',
    website: 'replo.app',
    industry: 'E-commerce',
    stage: 'Seed',
    funding: 8000000,
    signals: 'Medium',
    founders: ['Sean Osborn'],
    employees: 35,
    yearFounded: 2021,
  },
  {
    id: '12',
    name: 'Stacknize',
    description: 'Data platform for food and beverage companies.',
    website: 'stacknize.com',
    industry: 'Food & Beverage',
    stage: 'Series A',
    funding: 18000000,
    signals: 'Low',
    founders: ['David Ganz'],
    employees: 40,
    yearFounded: 2019,
  },
  {
    id: '13',
    name: 'Lynx',
    description: 'Financial crime prevention for fintechs.',
    website: 'lynx.money',
    industry: 'Fintech',
    stage: 'Series B',
    funding: 65000000,
    signals: 'High',
    founders: ['Henry Cai'],
    employees: 100,
    yearFounded: 2019,
  },
  {
    id: '14',
    name: 'Perforce',
    description: 'Enterprise software for code management and testing.',
    website: 'perforce.com',
    industry: 'Developer Tools',
    stage: 'Late Stage',
    funding: 1200000000,
    signals: 'High',
    founders: ['Christopher Seiwald'],
    employees: 800,
    yearFounded: 1995,
  },
  {
    id: '15',
    name: 'Mindstamp',
    description: 'Interactive video platform for marketing and education.',
    website: 'mindstamp.com',
    industry: 'MarTech',
    stage: 'Series A',
    funding: 10000000,
    signals: 'Medium',
    founders: ['David Knuppe'],
    employees: 30,
    yearFounded: 2017,
  },
  {
    id: '16',
    name: 'Axiom',
    description: 'Serverless analytics and data pipeline platform.',
    website: 'axiom.co',
    industry: 'Data & Analytics',
    stage: 'Series B',
    funding: 85000000,
    signals: 'High',
    founders: ['Martin Moder'],
    employees: 90,
    yearFounded: 2019,
  },
  {
    id: '17',
    name: 'Loom',
    description: 'Video messaging platform for work communication.',
    website: 'loom.com',
    industry: 'Productivity',
    stage: 'Late Stage',
    funding: 152500000,
    signals: 'High',
    founders: ['Joe Thomas'],
    employees: 200,
    yearFounded: 2015,
  },
  {
    id: '18',
    name: 'Brex',
    description: 'Corporate credit card and financial platform for companies.',
    website: 'brex.com',
    industry: 'Fintech',
    stage: 'Late Stage',
    funding: 12300000000,
    signals: 'High',
    founders: ['Henrique Dubugras', 'Pedro Franceschi'],
    employees: 2000,
    yearFounded: 2013,
  },
  {
    id: '19',
    name: 'Deel',
    description: 'Global payroll and HR platform for remote teams.',
    website: 'deel.com',
    industry: 'HR & People',
    stage: 'Series D',
    funding: 1170000000,
    signals: 'High',
    founders: ['Maksym Kulyk'],
    employees: 400,
    yearFounded: 2018,
  },
  {
    id: '20',
    name: 'Contrast Security',
    description: 'Application security platform with runtime protection.',
    website: 'contrastsecurity.com',
    industry: 'Security & Compliance',
    stage: 'Series C',
    funding: 240000000,
    signals: 'High',
    founders: ['Jeff Williams'],
    employees: 350,
    yearFounded: 2014,
  },
]
